name: Metrics

on:
    schedule:
        - cron: '0 0 * * *'

    workflow_dispatch:

    push:
        branches:
            - main

permissions: write-all

jobs:
    metrics:
        runs-on: ubuntu-20.04
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  plugin_traffic: yes
                  plugin_languages: yes
                  plugin_languages_indepth: yes
                  plugin_languages_ignored: html, css
                  plugin_languages_details: bytes-size, percentage
                  plugin_languages_sections: recently-used
