name: Metrics

on:
    schedule:
        - cron: '0 0 * * *'

    workflow_dispatch:

    push:
        branches:
            - main

permissions: write-all

jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  base_indepth: yes
                  plugin_traffic: yes
                  plugin_languages: yes
                  plugin_languages_indepth: yes
                  plugin_languages_ignored: html, css
                  plugin_languages_details: lines, percentage
                  plugin_languages_sections: recently-used
                  plugin_languages_recent_load: 1000
                  plugin_languages_recent_days: 365
